### ISSUE TITLE
Drop Symfony 4.4 support

### ISSUE THREAD

**Issue by oliverde8** [oliverde8/phpEtlBundle#3]
### Context

End of bug fixes for [Symfony 4.4 is on November 2022](https://symfony.com/releases/4.4). We should therefore stop supporting this version of symfony. 

### 
- [ ] Update all dependencies 
- [ ] [Update logger signature](https://github.com/oliverde8/phpEtlBundle/pull/2)

List is to be completed...

**Comment by mehdichaouch** [comment]
Hello @oliverde8,
I think this ticket is linked with PR #2 ?
And do you know when in November, because there is 30 days :)

**Comment by oliverde8** [comment]
Support was dropped
